# @package _global_
module:
  _target_: emg2qwerty.lightning.LSTMCTCModule
  in_features: 528
  mlp_features: [384]
  hidden_size: 384
  num_layers: 3
  dropout: 0.3
  bidirectional: true

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding: [1800, 200]

gaussian_noise:
  _target_: emg2qwerty.transforms.GaussianNoise
  std: 0.1

transforms:
  train:
    - ${to_tensor}
    - ${band_rotation}
    - ${temporal_jitter}
    - ${logspec}
    - ${specaug}
    - ${gaussian_noise}
  val:
    - ${to_tensor}
    - ${logspec}
  test: ${transforms.val}